" Set up the default colours to be dark
set background=dark
" Set Up an XDG compliant config
if empty($XDG_CACHE_HOME)
    let $XDG_CACHE_HOME="$HOME/.cache"
endif
if empty($XDG_CONFIG_HOME)
    let $XDG_CONFIG_HOME="$HOME/.config"
endif

set directory=$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
set undodir=$XDG_CACHE_HOME/vim,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

" Map leader and localleader key to comma
let mapleader = " "
let g:mapleader = " "
let maplocalleader = " "
let g:maplocalleader = " "


" Vim-Plug Scripts -------------------------------------
" Required:
call plug#begin(expand('$XDG_CACHE_HOME/vim/plugged'))

" Unite and modules
Plug 'Shougo/unite.vim'
Plug 'Shougo/unite-outline'
Plug 'Shougo/unite-help'
Plug 'Shougo/unite-session'


" Google CodeFmt
Plug 'google/maktaba'
Plug 'google/glaive'
Plug 'google/vim-codefmtlib', {'name' : 'codefmtlib' }
Plug 'google/vim-codefmt', {'name' : 'codefmt'}

" Tabular
Plug 'godlygeek/tabular'

" Fish shell script syntax highlighting
Plug 'dag/vim-fish'

" Git plugins
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'

" Vim Cursor Word
Plug 'itchyny/vim-cursorword'

!!@@plugs

" Required:
call plug#end()

" Required:
if has('autocmd')
    filetype plugin indent on
endif

" Configure Glaive
call glaive#Install()


" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has('syntax') && !exists('g:syntax_on')
    syntax on
endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set smartcase		" Do smart case matching
set incsearch		" Incremental search
set hlsearch		" Highlight search terms
set mouse=a		" Enable mouse usage (all modes)
set autoindent
set backspace=indent,eol,start

" Setup the display area
" Show the ruler and numbers
set ruler
" Show the line number on the current line and relative line numbers
" everywhere else.
set number
set relativenumber

set laststatus=2
set wildmenu

" Set the default wrapping and 80 column highlighting
set wrap
" set colorcolumn=81
2mat ErrorMsg '\%81v.'

set visualbell

if !&scrolloff
    set scrolloff=1
endif
if !&sidescrolloff
    set sidescrolloff=5
endif
set display+=lastline

set listchars=eol:⏎,trail:·,nbsp:⊙,tab:»·,extends:⇒,precedes:⇐
set list

if &encoding ==# 'latin1' && has('gui_running')
    set encoding=utf-8
endif


" Set the tab configuration
set shiftwidth=4
set tabstop=4
set expandtab
set smarttab


" Reload the file if modified outside of Vim
set autoread


" Configure Spelling
setglobal spell spelllang=en_au
autocmd FileType gitcommit,markdown setlocal spell

" Set the colours
set t_Co=256
"colorscheme refactor
colorscheme jellybeans

" Markdown
autocmd BufNewFile,BufFilePre,BufRead *.md,*.markdown,*.mdown,*.mkd,*.mkdn,README.md  set filetype=markdown

" Sort out the silly X11 clipboard
if has ('unnamedplus')
  set clipboard=unnamedplus
else
  set clipboard=unnamed
endif

"
" Unite configuration
"

" Use The Platinum Searcher for grepping
"if has('unix')
"    if executable('pt')
"      let g:unite_source_grep_command = 'pt'
"      let g:unite_source_grep_default_opts = '--nogroup --nocolor'
"      let g:unite_source_grep_recursive_opt = ''
"      let g:unite_source_grep_encoding = 'utf-8'
"    endif
"endif
"
" Use the fuzzy matcher for everything and sort them by rank
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_rank'])

" Map "<LEADER>u" to start Unite interactive
nnoremap <silent> <LEADER>u :<C-u>Unite<CR>
" Map "<LEADER>g" to Unite buffer search
nnoremap <silent> <LEADER>g :<C-u>Unite grep:. -buffer-name=search-buffer<CR>
" Map Control P to file searching
nnoremap <C-P> :Unite file_mru file_rec/async<CR>
" Map "<LEADER>/" to grep
nnoremap <LEADER>/ :Unite grep:.<CR>
" Map "<LEADER>y" to a yank ring esc setup.
let g:unite_source_history_yank_enable = 1
nnoremap <LEADER>y :Unite history/yank<CR>
" Map "<LEADER>s" to buffer switching
nnoremap <LEADER>s :Unite -quick-match buffer<CR>

" Insert the date and time for posts
map! <F5> <C-R>=strftime('%Y-%m-%d %H:%M:%S %z')<CR>

let base16colorspace=256
